version: '3.7'

services:
  # create a movies service
  movies:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    # prevent rebuild image on every code change
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
  
  movies-db:
    image: postgres:12-alpine
    # Persist the data beyond the life of the container
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=movies
      - POSTGRES_PASSWORD=movies
      - POSTGRES_DB=movies_dev

volumes:
  pg_data:
